// Code generated by MockGen. DO NOT EDIT.
// Source: internal/products/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/products/service.go -destination=internal/products/mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	products "github.com/shahzodshafizod/gocloud/internal/products"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetPartnerProducts mocks base method.
func (m *MockService) GetPartnerProducts(arg0 context.Context) (*products.GetAllResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartnerProducts", arg0)
	ret0, _ := ret[0].(*products.GetAllResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPartnerProducts indicates an expected call of GetPartnerProducts.
func (mr *MockServiceMockRecorder) GetPartnerProducts(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartnerProducts", reflect.TypeOf((*MockService)(nil).GetPartnerProducts), arg0)
}
